version: '3'
services:
  db:
    build: db
    shm_size: 1g
    env_file:
      - db/database.env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/Graphony/postgres-data
      - ./dbinit:/docker-entrypoint-initdb.d/
