name: Run Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz        
        python -m pip install --upgrade pip virtualenv
        virtualenv venv
        . venv/bin/activate
        pip install flake8 pytest pylint phmdoctest pygraphblas graphviz Pillow matplotlib
        python setup.py install
    - name: Lint
      run: |
        . venv/bin/activate
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      run: |
        . venv/bin/activate
        ./test.sh
